export {default as Types} from './types.json'
export {default as Status} from './status.json'
export {default as Ratings} from './ratings.json'
export {default as Producers} from './producers.json'
export {default as Genres} from './genres.json'
export {default as Xgenres} from './xGenres.json'
export {default as Themes} from './themes.json'
export {default as Demographics} from './demographics.json'